settings_version: 0.0.4
datasets_dir: \\172.20.95.50\bist-pattern\datasets
weights_dir: weights
runs_dir: runs
uuid: c8c9b74a72fd7825140f57873fab29bee81f6ca74ca4557a1fa92e3464fd4eac
sync: true
api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
